Whatsapp/Models/MasterServiceFeatures.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Whatsapp.Models
{
    public class MasterServiceFeatures
    {

        [Key]
        public Int64 FeatureID
        {
            get;
            set;
        }
        public string FeatureName { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public Int64 ServiceID { get; set; }

        [ForeignKey("ServiceID")]
        public MasterService MasterService { get; set; }

    }
}

Whatsapp/Controllers/MasterServiceFeaturesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Whatsapp.Interface;
using Whatsapp.Models;
using Whatsapp.Models.Data;
using Whatsapp.Models.ViewModel;

namespace Whatsapp.Controllers
{
    public class MasterServiceFeaturesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationContext _appcontext;
        private IRepository<Users> _users;
        public MasterServiceFeaturesController(ILogger<HomeController> logger, ApplicationContext appcontext, IRepository<Users> users)
        {
            _logger = logger;
            _appcontext = appcontext;
            this._users = users;
        }
        public IActionResult MasterServiceFeatureList()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetMasterServiceFeatureList()
        {
            List<MasterServiceFeatures> mf = new List<MasterServiceFeatures>();
            mf = await _appcontext.MasterServiceFeatures.ToListAsync().ConfigureAwait(false);
            return PartialView("~/Views/MasterServiceFeatures/PartialView/_MasterServiceFeatureList.cshtml", mf);
        }
        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            MasterServiceFeatures mf = null;
            if (id != 0)
            {
                mf = await _appcontext.MasterServiceFeatures
                    .Where(h => h.ServiceID == id)
                    .FirstOrDefaultAsync();
            }
            ViewData["ServiceData"] = new SelectList(_appcontext.MasterService.ToList(), "ServiceID", "ServiceName");
            return PartialView("~/Views/MasterServiceFeatures/PartialView/_Create.cshtml", mf);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MasterServiceFeatures mf)
        {
            if (ModelState.IsValid)
            {
                if (mf.FeatureID == 0)
                {
                    _appcontext.Add(mf);
                }
                else
                {
                    _appcontext.Update(mf);
                }
                await _appcontext.SaveChangesAsync();
                return View("MasterServiceFeatureList");
            }
            return Json(mf);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            MasterServiceFeatures mf = new MasterServiceFeatures();
            mf = await _appcontext.MasterServiceFeatures.Where(a => a.FeatureID == id).FirstOrDefaultAsync().ConfigureAwait(false);
            _appcontext.MasterServiceFeatures.Remove(mf);
            await _appcontext.SaveChangesAsync();
            return View("MasterServiceFeatureList");
        }
    }
}

Whatsapp/Views/MasterServiceFeatures/PartialView/_Create.cshtml
@model Whatsapp.Models.MasterServiceFeatures


<div class="card">
    <div class="card-header">
        <h4>
            Add Service Feature<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </h4>
    </div>
    <div class="card-body">
        <form method="post" class="form-block" asp-action="Create" asp-controller="MasterServiceFeatures">
            <div class="row">
                @if (Model == null)
                {
                    <input type="hidden" asp-for="FeatureID" value="0" />
                }
                else
                {
                    <input type="hidden" asp-for="FeatureID" value="@Model.FeatureID" />
                }

                <div class="form-group col-sm-6">
                    <label>Service Name</label>
                    <select asp-for="ServiceID"  class="custom-select form-control" asp-items="ViewBag.ServiceData">
                        <option id="0"> -- Select Service -- </option>
                    </select>
                </div>
                <div class="form-group col-sm-6">
                    <label>Feature Name</label>
                    <input type="text" class="form-control" asp-for="FeatureName" placeholder="Enter SCode">
                </div>
                <div class="form-group col-sm-6">
                    <label>Remark</label>
                    <input type="text" class="form-control" asp-for="Remark" placeholder="Enter Remark">
                </div>
                <div class="form-group col-sm-6">
                    <input class="form-check-input ml-sm-2 mt-sm-5" type="checkbox" asp-for="IsActive">
                    <label class="form-check-label ml-sm-4 mt-sm-5" for="IsActive">
                        IsActive
                    </label>
                </div>
            </div>
            <div class="row justify-content-center">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
</div>

Whatsapp/Views/MasterServiceFeatures/PartialView/_MasterServiceFeatureList.cshtml
@using Whatsapp.Models.Data;
@model List<MasterServiceFeatures>
@if (Model != null && Model.Any())
{
    int i = 1;
    @foreach (var item in Model)
    {
        <tr>
            <td>@i</td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FeatureID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FeatureName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remark)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                <button onclick="RenderForm(@item.FeatureID)" class="btn btn-primary btn-sm editbtn" data-toggle="modal" data-target="#exampleModalCenter">
                   <i class="fa fa-edit"></i>
                </button>
                <a href="/MasterServiceFeatures/Delete/@item.FeatureID" class="btn btn-danger btn-sm deletbtn">
                    <i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
        i++;
    }

}
else
{
    <tr>
        <td colspan="3">No Records Found</td>
    </tr>
}